services:
  api:
    build:
      context: ./apps/api
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORDS_SALT_SECRET_KEY: ${PASSWORDS_SALT_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USE_TLS: ${SMTP_USE_TLS}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      ENV: ${ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_TRACES_SAMPLE_RATE: ${SENTRY_TRACES_SAMPLE_RATE}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      METRICS_TOKEN: ${METRICS_TOKEN}

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://creda-api.ihorsavenko.com
        NEXT_PUBLIC_ENABLE_ANALYTICS: "true"
    environment:
      INTERNAL_API_URL: http://api:8000
    ports:
      - "3000"
